---
- name: Create empty cluster
  uri:
    url: "{{ ambari_server_protocol }}://{{ ambari_server_hostname }}:{{ ambari_server_port }}/api/v1/clusters/{{ cluster_name }}"
    method: POST
    force_basic_auth: yes
    user: "{{ ambari_username }}"
    password: "{{ ambari_password }}"
    headers: '{"X-Requested-By":"ambari", "Content-Type": "application/x-www-form-urlencoded"}'
    body: '{"Clusters": {"cluster_name": "{{ cluster_name }}", "version":"HDP-2.6"}}'
    body_format: json
    validate_certs: no
    status_code: 200,201,202
    return_content: yes
  register: create_cluster
  no_log: False
  ignore_errors: True

- name: Cluster already exists
  pause: prompt='Please confirm you want to continue cluster {{ cluster_name }} already installed ! Press return to continue. Press Ctrl+c and then "a" to abort'
  when: create_cluster.status == 409

- name: Error on cluster creation
  pause: prompt='Something went wrong with creation of cluster {{ cluster_name }}. Do you want to continue? Press return to continue. Press Ctrl+c and then "a" to abort'
  when: create_cluster.status not in [200,201,202,409]

- name: Copy VDF repository
  template: >
   src=roles/ambari-cluster/templates/repo.xml.j2
   dest=/tmp/repo.xml

- name: Load VDF repository
  uri:
    url: "{{ ambari_server_protocol }}://{{ ambari_server_hostname }}:{{ ambari_server_port }}/api/v1/version_definitions"
    method: POST
    force_basic_auth: yes
    user: "admin"
    password: "admin"
    headers: '{"X-Requested-By":"ambari", "Content-Type": "application/x-www-form-urlencoded"}'
    body: '{"VersionDefinition": {"version_url": "file:/tmp/repo.xml"}}'
    body_format: json
    validate_certs: no
    status_code: 200,201,202
    return_content: yes
  register: register_vdf
  no_log: True
  ignore_errors: True

- name: VDF already exists
  pause: prompt='Please confirm you want to continue, VDF repository already installed ! Press return to continue. Press Ctrl+c and then "a" to abort'
  when: register_vdf.status == 500

- name: Load RedHat Satellite/Spacewalk
  uri:
    url: "{{ ambari_server_protocol }}://{{ ambari_server_hostname }}:{{ ambari_server_port }}/api/v1/stacks/HDP/versions/{{stack_version}}/repository_versions/1"
    method: PUT
    force_basic_auth: yes
    user: "{{ ambari_username }}"
    password: "{{ ambari_password }}"
    headers: '{"X-Requested-By":"ambari", "Content-Type": "application/x-www-form-urlencoded"}'
    body: "{{ lookup('template','templates/repository_versions/{{ stack_version_id }}.json.j2') }}"
    body_format: json
    validate_certs: no
    status_code: 200,201,202
    return_content: yes
  register: register_satellite_repo
  ignore_errors: True
  when: sattelite_repo

- name: Load default configuration
  uri:
    url: "{{ ambari_server_protocol }}://{{ ambari_server_hostname }}:{{ ambari_server_port }}/api/v1/clusters/{{ cluster_name }}"
    method: PUT
    force_basic_auth: yes
    user: "{{ ambari_username }}"
    password: "{{ ambari_password }}"
    headers: '{"X-Requested-By":"ambari", "Content-Type": "application/x-www-form-urlencoded"}'
    body: "{{ lookup('template','templates/{{ item }}.json.j2') }}"
    body_format: json
    validate_certs: no
    status_code: 200,201,202
    return_content: yes
  with_items:
   - "{{ base_cluster.conf }}"
  when: create_cluster.status != 409

- name: Activate cluster
  uri:
    url: "{{ ambari_server_protocol }}://{{ ambari_server_hostname }}:{{ ambari_server_port }}/api/v1/clusters/{{ cluster_name }}"
    method: PUT
    force_basic_auth: yes
    user: "{{ ambari_username }}"
    password: "{{ ambari_password }}"
    headers: '{"X-Requested-By":"ambari", "Content-Type": "application/x-www-form-urlencoded"}'
    body: '{"Clusters":{"provisioning_state":"INSTALLED"}}'
    body_format: json
    validate_certs: no
    status_code: 200,201,202
    return_content: yes
  when: create_cluster.status != 409
