---
######## Install hdp-select ###############
- template:
    src: templates/repository_versions/hdp.repo.j2
    dest: /etc/yum.repos.d/hdp.repo
  delegate_to: "{{ item }}"
  when: hdp_repo_path is not defined
  with_items:
    - "{{ cluster_hosts }}"

- copy:
    src: "{{hdp_repo_path}}"
    dest: /etc/yum.repos.d/hdp.repo
  delegate_to: "{{ item }}"
  when: hdp_repo_path is defined
  with_items:
    - "{{ cluster_hosts }}"

- name: Ensure software is installed (yum)
  yum: name="hdp-select" state=present update_cache=yes
  delegate_to: "{{ item }}"
  with_items:
    - "{{ cluster_hosts }}"
####################################################
