---
# Check variables/layout
- include: check_variables.yml

# Create base cluster
- include: create_base_cluster.yml

# Deploy cluster
- include: deploy_cluster.yml

# Trigger cluster
- include: trigger_cluster_installation.yml

# Keberize
- include: enable_kerberos.yml
  when: cluster_services.KERBEROS is defined and cluster_services.KERBEROS

# Actions before starting
- include: pre_start.yml

# Start cluster
- include: start_cluster.yml

# Actions after starting
- include: post_start.yml

# Smoke test
#- include: smoke_test.yml
