---
# Check variables/layout
# - include: check_variables.yml

# Deploy HDP repository
- include: deploy_repos.yml

# Actions beforce installing
- include: pre_install.yml

# Create base cluster
- include: create_base_cluster.yml

# Deploy cluster
- include: deploy_cluster.yml

# Trigger cluster
- include: trigger_cluster_installation.yml

# Kerberize
- include: enable_kerberos.yml
  when: cluster_services.KERBEROS is defined

# Actions before starting
- include: pre_start.yml

# Start cluster
- include: start_cluster.yml

# Actions after starting
- include: post_start.yml

# Smoke test
- include: smoke_test.yml
  when: cluster_services.SMOKETEST is defined
