- name: Register components on hosts
  uri:
    url: "{{ ambari_server_protocol }}://{{ ambari_server_hostname }}:{{ ambari_server_port }}/api/v1/clusters/{{ cluster_name }}/hosts?Hosts/host_name={{ hosts }}"
    method: POST
    force_basic_auth: yes
    user: "{{ ambari_username }}"
    password: "{{ ambari_password }}"
    headers: '{"X-Requested-By":"ambari", "Content-Type": "application/x-www-form-urlencoded"}'
    body: '{"host_components":[{"HostRoles":{"component_name":"{{ in_item.1 }}"}}]}'
    body_format: json
    validate_certs: no
    # status_code: 200,201,202
    return_content: no
  with_subelements:
    - "{{ services }}"
    - components.noha
  register: registration
  loop_control:
    label: in_item.1
    loop_var: in_item
  when: in_item.1 != "" and hosts in groups[in_item.1]
  ignore_errors: True
  no_log: True

- fail:
    msg: "{{ fail_item.status }}: Components {{ fail_item.in_item[1] }} already registred on the hosts"
  with_items:
    - "{{ registration.results }}"
  loop_control:
    loop_var: fail_item
    label: "{{ fail_item.in_item[1] }} on {{ hosts }}"
  when: fail_item.status is defined and fail_item.status == 409
  ignore_errors: True

- name: Register HA components on hosts
  uri:
    url: "{{ ambari_server_protocol }}://{{ ambari_server_hostname }}:{{ ambari_server_port }}/api/v1/clusters/{{ cluster_name }}/hosts?Hosts/host_name={{ hosts }}"
    method: POST
    force_basic_auth: yes
    user: "{{ ambari_username }}"
    password: "{{ ambari_password }}"
    headers: '{"X-Requested-By":"ambari", "Content-Type": "application/x-www-form-urlencoded"}'
    body: '{"host_components":[{"HostRoles":{"component_name":"{{ in_item.1 }}"}}]}'
    body_format: json
    validate_certs: no
    # status_code: 200,201,202
    return_content: no
  with_subelements:
    - "{{ services }}"
    - components.ha
  register: registration
  loop_control:
    label: in_item.1
    loop_var: in_item
  when: in_item.1 != "" and hosts in groups[in_item.1]
  ignore_errors: True
  no_log: True

- fail:
    msg: "{{ fail_item.status }}: Components {{ fail_item.in_item[1] }} already registred on the hosts"
  with_items:
    - "{{ registration.results }}"
  loop_control:
    loop_var: fail_item
    label: "{{ fail_item.in_item[1] }} on {{ hosts }}"
  when: fail_item.status is defined and fail_item.status == 409
  ignore_errors: True

- name: Register clients components on hosts
  uri:
    url: "{{ ambari_server_protocol }}://{{ ambari_server_hostname }}:{{ ambari_server_port }}/api/v1/clusters/{{ cluster_name }}/hosts?Hosts/host_name={{ hosts }}"
    method: POST
    force_basic_auth: yes
    user: "{{ ambari_username }}"
    password: "{{ ambari_password }}"
    headers: '{"X-Requested-By":"ambari", "Content-Type": "application/x-www-form-urlencoded"}'
    body: '{"host_components":[{"HostRoles":{"component_name":"{{ in_item.1 }}"}}]}'
    body_format: json
    validate_certs: no
    # status_code: 200,201,202
    return_content: no
  with_subelements:
    - "{{ services }}"
    - components.client
  register: registration
  loop_control:
    label: in_item.1
    loop_var: in_item
  when: in_item.1 != "" and hosts in groups[in_item.1]
  ignore_errors: True
  no_log: True

- fail:
    msg: "{{ fail_item.status }}: Components {{ fail_item.in_item[1] }} already registred on the hosts"
  with_items:
    - "{{ registration.results }}"
  loop_control:
    loop_var: fail_item
    label: "{{ fail_item.in_item[1] }} on {{ hosts }}"
  when: fail_item.status is defined and fail_item.status == 409
  ignore_errors: True
