- hosts: admin1
  gather_facts: yes

  roles:
    - role: ambari-cluster
      vars:
        ambari_server_hostname: admin1
        ambari_server_port: 7443
        ambari_server_protocol: https
        cluster_name: dev01                 ## without special caracter, space, underscore...
        ambari_username: admin
        ambari_password: admin
        cluster_hosts: "{{ groups['MYCLUSTER'] }}"
        repos_url_hdp: "http://my_repo_url/HDP/centos7/2.6.4.0-91/"
        repos_url_hdp_utils: "http://my_repo_url/UTIL/"
        first_namenode: "{{ groups['NAMENODE'][0] }}"
        second_namenode: "{{ groups['NAMENODE'][1] }}"
        zookeeper_quorum: "{{ groups['ZOOKEEPER_SERVER'] }}"
        hdp_namenode_dir:
          - "/data/nn"
        hdp_datanode_dir:
          - "/data/hdfs/data/1"
          - "/data/hdfs/data/2"
          - "/data/hdfs/data/3"
          - "/data/hdfs/data/4"
        hdp_checkpoint_dir:
          - "/data/checkpoint"
        hdp_journalnode_dir:
          - "/data/journalnode"
        hdp_yarn_local_dir:
          - "/data/yarn/local/1"
          - "/data/yarn/local/2"
        hdp_yarn_log_dir:
          - "/data/yarn/log/2"
          - "/data/yarn/log/2"
        database_type: mysql
        database_server: admin1
        database_hive: hive_db
        database_hive_user: hive
        database_hive_user_password: hive123
        database_ranger: ranger_db
        database_ranger_user: ranger
        database_ranger_user_password: ranger123
        database_oozie: oozie_db
        database_oozie_user: oozie
        database_oozie_user_password: oozie123
        ranger_admin_password: test12345678
        ssl_truststore_path: "/etc/security/serverKeys/truststore.jks"
        ssl_truststore_password: truststore123
        ssl_keystore_path: "/etc/security/serverKeys/keystore.jks"
        ssl_keystore_password: keystore123
        ranger_truststore_alias: "master1"
        ranger_keystore_credential_alias: "master1"
        ranger_keystore_keyalias: "master1"
        hst_agent_version: "1.4.5.2.6.2.2-1"  ## Must match your package version
        cluster_services:
          HDFS:
            HA: True
            SSL: True
          YARN:
            HA: True
            SSL: True
          MAPREDUCE2:
            SSL: True
          TEZ:
            SSL: True
          PIG:
          SLIDER:
          ZOOKEEPER:
          HIVE:
          RANGER:
            PLUGIN:
              HDFS: True
              YARN: True
              HIVE: True
          AMBARI_INFRA:
          AMBARI_METRICS:
          KAFKA:
          SPARK2:
            SSL: True
          OOZIE:
          SMARTSENSE:
